/* Development-only persistent virtual pointer for headless Wayland playtests.
 * Build with wlr-virtual-pointer client code generated by wayland-scanner.
 * A FIFO accepts `move X Y`, `click X Y`, `press`, `release`, and `quit`.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>
#include "wlr-virtual-pointer.h"
#include "virtual-keyboard.h"

static struct zwlr_virtual_pointer_manager_v1 *manager;
static struct zwp_virtual_keyboard_manager_v1 *keyboard_manager;
static struct wl_seat *seat;
static void global(void *data, struct wl_registry *registry, uint32_t name,
                   const char *interface, uint32_t version) {
    (void)data;
    if (!strcmp(interface, "zwlr_virtual_pointer_manager_v1"))
        manager = wl_registry_bind(registry, name,
             &zwlr_virtual_pointer_manager_v1_interface, version > 2 ? 2 : version);
    if (!strcmp(interface, "zwp_virtual_keyboard_manager_v1"))
        keyboard_manager = wl_registry_bind(registry, name,
             &zwp_virtual_keyboard_manager_v1_interface, 1);
    if (!strcmp(interface, "wl_seat"))
        seat = wl_registry_bind(registry, name, &wl_seat_interface, 1);
}
static void remove_global(void *data, struct wl_registry *registry, uint32_t name) {
    (void)data; (void)registry; (void)name;
}
static uint32_t milliseconds(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint32_t)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}
int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "Usage: platform-pointer FIFO [width height]\n"); return 1; }
    uint32_t width = argc > 2 ? atoi(argv[2]) : 1440;
    uint32_t height = argc > 3 ? atoi(argv[3]) : 900;
    struct wl_display *display = wl_display_connect(NULL);
    if (!display) { perror("connect Wayland"); return 1; }
    struct wl_registry *registry = wl_display_get_registry(display);
    const struct wl_registry_listener listener = {global, remove_global};
    wl_registry_add_listener(registry, &listener, NULL);
    wl_display_roundtrip(display);
    if (!manager) { fprintf(stderr, "Compositor lacks virtual-pointer protocol\n"); return 1; }
    struct zwlr_virtual_pointer_v1 *pointer = zwlr_virtual_pointer_manager_v1_create_virtual_pointer(manager, NULL);
    struct zwp_virtual_keyboard_v1 *keyboard = NULL;
    if (keyboard_manager && seat) {
        keyboard = zwp_virtual_keyboard_manager_v1_create_virtual_keyboard(keyboard_manager, seat);
        struct xkb_context *context = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
        const struct xkb_rule_names names = {.rules="evdev", .model="pc105", .layout="us"};
        struct xkb_keymap *map = xkb_keymap_new_from_names(context, &names, XKB_KEYMAP_COMPILE_NO_FLAGS);
        char *text = xkb_keymap_get_as_string(map, XKB_KEYMAP_FORMAT_TEXT_V1);
        size_t length = strlen(text) + 1;
        int fd = memfd_create("platform-keymap", MFD_CLOEXEC);
        if (fd < 0 || write(fd, text, length) != (ssize_t)length) { perror("create keymap"); return 1; }
        zwp_virtual_keyboard_v1_keymap(keyboard, WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1, fd, length);
        zwp_virtual_keyboard_v1_modifiers(keyboard, 0, 0, 0, 0);
        close(fd);
        free(text);
        xkb_keymap_unref(map);
        xkb_context_unref(context);
    }
    wl_display_roundtrip(display);
    mkfifo(argv[1], 0600);
    FILE *commands = fopen(argv[1], "r+");
    if (!commands) { perror("open FIFO"); return 1; }
    char line[256], command[32];
    uint32_t x, y;
    while (fgets(line, sizeof(line), commands)) {
        command[0] = 0;
        int fields = sscanf(line, "%31s %u %u", command, &x, &y);
        if (!strcmp(command, "quit")) break;
        if ((!strcmp(command, "key") || !strcmp(command, "hold") || !strcmp(command, "press") || !strcmp(command, "release")) && fields >= 2 && keyboard) {
            uint32_t state = !strcmp(command, "release") ? WL_KEYBOARD_KEY_STATE_RELEASED : WL_KEYBOARD_KEY_STATE_PRESSED;
            zwp_virtual_keyboard_v1_key(keyboard, milliseconds(), x, state);
            wl_display_roundtrip(display);
            if (!strcmp(command, "key") || !strcmp(command, "hold")) {
                uint32_t hold_ms = fields == 3 ? y : 60;
                usleep((hold_ms > 30000 ? 30000 : hold_ms) * 1000);
                zwp_virtual_keyboard_v1_key(keyboard, milliseconds(), x, WL_KEYBOARD_KEY_STATE_RELEASED);
                wl_display_roundtrip(display);
            }
            continue;
        }
        if (!strcmp(command, "size") && fields == 3) {
            width = x; height = y;
            continue;
        }
        if (fields == 3) {
            zwlr_virtual_pointer_v1_motion_absolute(pointer, milliseconds(), x, y, width, height);
            zwlr_virtual_pointer_v1_frame(pointer);
            wl_display_roundtrip(display);
            usleep(40000);
        }
        if (!strcmp(command, "click") || !strcmp(command, "press")) {
            zwlr_virtual_pointer_v1_button(pointer, milliseconds(), 272, 1);
            zwlr_virtual_pointer_v1_frame(pointer);
            wl_display_roundtrip(display);
        }
        if (!strcmp(command, "click")) usleep(60000);
        if (!strcmp(command, "click") || !strcmp(command, "release")) {
            zwlr_virtual_pointer_v1_button(pointer, milliseconds(), 272, 0);
            zwlr_virtual_pointer_v1_frame(pointer);
            wl_display_roundtrip(display);
        }
    }
    fclose(commands);
    zwlr_virtual_pointer_v1_destroy(pointer);
    if (keyboard) zwp_virtual_keyboard_v1_destroy(keyboard);
    wl_display_disconnect(display);
    unlink(argv[1]);
    return 0;
}
