/* Development-only persistent virtual pointer for headless Wayland playtests.
 * Build with wlr-virtual-pointer client code generated by wayland-scanner.
 * A FIFO accepts `move X Y`, `click X Y`, `press`, `release`, and `quit`.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <time.h>
#include <sys/stat.h>
#include <wayland-client.h>
#include "wlr-virtual-pointer.h"

static struct zwlr_virtual_pointer_manager_v1 *manager;
static void global(void *data, struct wl_registry *registry, uint32_t name,
                   const char *interface, uint32_t version) {
    (void)data;
    if (!strcmp(interface, "zwlr_virtual_pointer_manager_v1"))
        manager = wl_registry_bind(registry, name,
             &zwlr_virtual_pointer_manager_v1_interface, version > 2 ? 2 : version);
}
static void remove_global(void *data, struct wl_registry *registry, uint32_t name) {
    (void)data; (void)registry; (void)name;
}
static uint32_t milliseconds(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint32_t)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}
int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "Usage: platform-pointer FIFO [width height]\n"); return 1; }
    uint32_t width = argc > 2 ? atoi(argv[2]) : 1440;
    uint32_t height = argc > 3 ? atoi(argv[3]) : 900;
    struct wl_display *display = wl_display_connect(NULL);
    if (!display) { perror("connect Wayland"); return 1; }
    struct wl_registry *registry = wl_display_get_registry(display);
    const struct wl_registry_listener listener = {global, remove_global};
    wl_registry_add_listener(registry, &listener, NULL);
    wl_display_roundtrip(display);
    if (!manager) { fprintf(stderr, "Compositor lacks virtual-pointer protocol\n"); return 1; }
    struct zwlr_virtual_pointer_v1 *pointer = zwlr_virtual_pointer_manager_v1_create_virtual_pointer(manager, NULL);
    wl_display_roundtrip(display);
    mkfifo(argv[1], 0600);
    FILE *commands = fopen(argv[1], "r+");
    if (!commands) { perror("open FIFO"); return 1; }
    char line[256], command[32];
    uint32_t x, y;
    while (fgets(line, sizeof(line), commands)) {
        command[0] = 0;
        int fields = sscanf(line, "%31s %u %u", command, &x, &y);
        if (!strcmp(command, "quit")) break;
        if (!strcmp(command, "size") && fields == 3) {
            width = x; height = y;
            continue;
        }
        if (fields == 3) {
            zwlr_virtual_pointer_v1_motion_absolute(pointer, milliseconds(), x, y, width, height);
            zwlr_virtual_pointer_v1_frame(pointer);
            wl_display_roundtrip(display);
            usleep(40000);
        }
        if (!strcmp(command, "click") || !strcmp(command, "press")) {
            zwlr_virtual_pointer_v1_button(pointer, milliseconds(), 272, 1);
            zwlr_virtual_pointer_v1_frame(pointer);
            wl_display_roundtrip(display);
        }
        if (!strcmp(command, "click")) usleep(60000);
        if (!strcmp(command, "click") || !strcmp(command, "release")) {
            zwlr_virtual_pointer_v1_button(pointer, milliseconds(), 272, 0);
            zwlr_virtual_pointer_v1_frame(pointer);
            wl_display_roundtrip(display);
        }
    }
    fclose(commands);
    zwlr_virtual_pointer_v1_destroy(pointer);
    wl_display_disconnect(display);
    unlink(argv[1]);
    return 0;
}
